/// Authored story data; progress, inventory and scheduling live in Game.
class ResidentStoryBeat {
  final String id, title, request, success;
  final String? potionId, alternativeText;
  final bool optional;
  final List<String> revealedFactIds, introducedResidentIds;
  const ResidentStoryBeat({required this.id, required this.title,
    required this.request, required this.success, this.potionId,
    this.optional = false, this.alternativeText,
    this.revealedFactIds = const [], this.introducedResidentIds = const []});
}

class ResidentDefinition {
  final String id, name, occupation, personality, speech, want, entryCondition;
  final Map<String, String> facts;
  final List<ResidentStoryBeat> story;
  const ResidentDefinition({required this.id, required this.name,
    required this.occupation, required this.personality, required this.speech,
    required this.want, required this.facts, required this.story,
    this.entryCondition = 'always'});
}

const residents = <ResidentDefinition>[
  ResidentDefinition(id: 'robin', name: '로빈', occupation: '약초 상인',
    personality: '조용하고 세심하게 돌보며, 받은 도움을 기억해요.',
    speech: '조금만, 잘 자랐어요 같은 완곡한 말을 써요.',
    want: '새벽 일을 앞두고 쉬고, 스승에게 받은 씨앗을 키우고 싶어요.',
    facts: {
      'robin.dawn': '로빈은 새벽마다 밭의 약초를 돌본다.',
      'robin.seed': '스승에게 받은 살아 있는 씨앗이 아직 싹트지 않았다.',
      'robin.share': '로빈은 첫 싹을 혼자 간직하기보다 이웃과 나누고 싶어 한다.',
    }, story: [
      ResidentStoryBeat(id: 'robin.rest', title: '새벽 밭을 위한 휴식', potionId: 'sleep',
        request: '새벽에 약초를 돌봐야 하는데, 요즘 푹 자지를 못했어요. 숙면 물약 한 병 부탁해요.',
        success: '덕분에 잘 잤어요. 오늘 새벽에는 밭의 작은 잎도 찬찬히 살펴봤답니다.',
        revealedFactIds: ['robin.dawn']),
      ResidentStoryBeat(id: 'robin.seed', title: '스승이 남긴 씨앗', potionId: 'sprout',
        request: '스승님 씨앗을 아껴 뒀는데, 봄이 와도 조용하네요. 살아 있는 씨앗의 싹을 깨울 약이 있을까요?',
        success: '작은 잎이 나왔어요! 시간을 기다리는 것도 돌봄이었나 봐요.',
        revealedFactIds: ['robin.seed'], introducedResidentIds: ['sage']),
      ResidentStoryBeat(id: 'robin.share', title: '나누는 첫 싹',
        request: '제 몫만 남기지 않고 이웃에게도 나누고 싶어요. 세이지의 씨앗 교환회 이야기를 들었나요?',
        success: '씨앗과 키우는 법을 함께 나눴어요. 모르는 건 서로 적어 두었고요.',
        revealedFactIds: ['robin.share'], introducedResidentIds: ['sage']),
      ResidentStoryBeat(id: 'robin.ending', title: '누군가의 첫 씨앗',
        request: '이번엔 저도 누군가의 첫 씨앗을 챙겼어요. 새 잎 소식을 전하러 왔답니다.',
        success: '로빈은 밭을 돌보며 이웃과 씨앗을 나누고 있어요.'),
    ]),
  ResidentDefinition(id: 'mina', name: '미나', occupation: '제빵사',
    personality: '활기차지만 남을 챙기다 자신의 휴식을 미뤄요.',
    speech: '따끈하게, 한 조각 더 같은 빵집의 말을 즐겨 써요.',
    want: '첫 빵부터 마지막 빵까지 잘 굽고, 자신도 앉아서 쉬고 싶어요.',
    facts: {
      'mina.dawn': '미나는 새벽에 반죽을 준비한다.',
      'mina.cold': '차가운 반죽상자 때문에 빵이 고르게 부풀지 않는다.',
      'mina.chair': '미나는 가게 구석에 자신이 쉴 의자를 놓기로 했다.',
    }, story: [
      ResidentStoryBeat(id: 'mina.rest', title: '반죽이 부푸는 동안', potionId: 'sleep',
        request: '내일 새벽에 반죽을 해야 해요. 오늘은 편히 잘 수 있게 숙면 물약 한 병 주세요.',
        success: '반죽이 부푸는 동안 저도 푹 쉬었어요. 그런데 상자는 아직 차갑네요.',
        revealedFactIds: ['mina.dawn']),
      ResidentStoryBeat(id: 'mina.warmth', title: '반죽상자의 온기', potionId: 'warmth',
        request: '반죽상자에 감싼 천이 은근히 따뜻하면 좋겠어요. 마시는 약 말고, 천에 쓸 온기 물약을 부탁해요.',
        success: '오늘은 첫 빵과 마지막 빵이 같이 부풀었어요. 덮개 수선은 루나에게 부탁할래요.',
        revealedFactIds: ['mina.cold'], introducedResidentIds: ['luna']),
      ResidentStoryBeat(id: 'mina.corner', title: '쉬어 가는 구석', potionId: 'calm_scent',
        optional: true, alternativeText: '향 없이 쉴 자리를 준비해요',
        request: '구석에 작은 의자를 놓았어요. 은은한 향을 두어도 좋고, 빵 냄새만 남겨도 좋겠어요.',
        success: '잠깐 앉아서 숨을 돌렸어요. 향이 있든 없든, 이 자리는 제 것이네요.',
        revealedFactIds: ['mina.chair']),
      ResidentStoryBeat(id: 'mina.ending', title: '앉아서 먹는 빵',
        request: '오늘은 제 빵도 앉아서 먹으려고요. 나리의 책모임에 보낼 간식도 조금 챙겼답니다.',
        success: '미나는 이웃에게 빵을 나누고 자신을 위한 휴식도 남겨 둬요.',
        introducedResidentIds: ['nari']),
    ]),
  ResidentDefinition(id: 'ellie', name: '엘리', occupation: '숲길 안내인',
    personality: '정확하고 책임감이 강해 다른 사람의 길도 살펴요.',
    speech: '갈림길부터 확인할게요, 한 걸음씩 가요라고 말해요.',
    want: '안내인 혼자 뛰어다니지 않아도 사람들이 길을 찾길 바라요.',
    facts: {
      'ellie.night': '엘리는 횃불이 꺼진 밤길의 표지를 읽어야 한다.',
      'ellie.signs': '엘리는 처음 온 사람도 볼 수 있는 빛나는 표지를 원한다.',
      'ellie.share': '엘리는 새 안내인에게 앞장설 기회를 주고 싶다.',
    }, story: [
      ResidentStoryBeat(id: 'ellie.sight', title: '밤길의 작은 글씨', potionId: 'sight',
        request: '횃불 없이도 밤 숲길을 보고 싶어요. 어두운 표지판을 읽을 시야 물약이 필요해요.',
        success: '표지판의 작은 글씨까지 보여요. 밤 배달을 시작한 준에게도 이 가게를 알려 줄게요.',
        revealedFactIds: ['ellie.night'], introducedResidentIds: ['jun']),
      ResidentStoryBeat(id: 'ellie.signs', title: '모두의 길표지', potionId: 'pathlight',
        request: '저만 잘 보는 것으론 부족하더라고요. 표지판에 붙여 은은하게 빛나는 약을 부탁해요.',
        success: '이번엔 새 안내인도 갈림길을 찾았어요. 루나의 수지 설명도 도움이 됐죠.',
        revealedFactIds: ['ellie.signs'], introducedResidentIds: ['luna']),
      ResidentStoryBeat(id: 'ellie.route', title: '수문으로 이어진 길',
        request: '도란과 수문 옆 길도 확인해 볼게요. 물약이 길 점검을 대신해 주는 건 아니니까요.',
        success: '도란이 직접 점검한 길을 함께 걸었어요. 이제 안내를 나눌 수 있겠네요.',
        revealedFactIds: ['ellie.share'], introducedResidentIds: ['doran']),
      ResidentStoryBeat(id: 'ellie.ending', title: '뒤에서 걷는 안내인',
        request: '오늘은 제가 뒤에서 따라 걸었어요. 조합에도 새 길의 소식을 전할게요.',
        success: '엘리는 이웃과 안내를 나누며 숲길을 돌보고 있어요.'),
    ]),
  ResidentDefinition(id: 'jun', name: '준', occupation: '견습 우편배달부',
    entryCondition: 'sightFeedback',
    personality: '서두르다 스스로 돌아보며, 맡긴 물건을 소중히 여겨요.',
    speech: '빠르게 말하다 아, 이번엔 확인했어요! 하고 덧붙여요.',
    want: '빠르다는 칭찬보다 편지가 무사히 도착했다는 말을 듣고 싶어요.',
    facts: {
      'jun.address': '준은 밤에도 집 앞 주소를 읽어야 한다.',
      'jun.parcel': '준은 유리 소포를 급히 내려놓았다가 놀란 적이 있다.',
      'jun.rain': '준은 망토뿐 아니라 편지도 비를 막아 줘야 한다고 깨달았다.',
    }, story: [
      ResidentStoryBeat(id: 'jun.address', title: '또렷한 주소', potionId: 'sight',
        request: '엘리 소개로 왔어요. 밤에도 주소가 보이도록 시야 물약 한 병 주세요.',
        success: '이번에는 같은 골목을 세 번 돌지 않았어요. 아, 주소도 다시 확인했어요!',
        revealedFactIds: ['jun.address']),
      ResidentStoryBeat(id: 'jun.parcel', title: '살며시 내려놓기', potionId: 'softfall',
        request: '상자를 내려놓다 쿵 했어요. 빨라지는 약보다 작은 소포가 살며시 떨어지는 약이 필요해요.',
        success: '소포가 부드럽게 내려왔어요. 저도 급히 던지지 않고 두 손으로 받쳤고요.',
        revealedFactIds: ['jun.parcel']),
      ResidentStoryBeat(id: 'jun.rain', title: '편지의 우산', potionId: 'raincoat',
        optional: true, alternativeText: '비를 피하는 배달길로 가요',
        request: '이번엔 봉투가 젖을까 걱정이에요. 방수약을 쓰거나, 처마 아래로 천천히 돌아가도 되겠죠?',
        success: '편지가 무사히 도착했어요. 망토만 아니라 편지에도 우산이 필요했네요.',
        revealedFactIds: ['jun.rain'], introducedResidentIds: ['luna']),
      ResidentStoryBeat(id: 'jun.ending', title: '잘 받았다는 말',
        request: '빨랐다는 말보다 잘 받았다는 말이 더 좋네요. 이번엔 나리의 책모임 초대장을 가져왔어요.',
        success: '준은 천천히 확인하며 이웃의 편지를 전하고 있어요.',
        introducedResidentIds: ['nari']),
    ]),
  ResidentDefinition(id: 'sage', name: '세이지', occupation: '희귀 재료 상인',
    entryCondition: 'guildCompleted',
    personality: '거래 조건을 명확히 말하고 희귀함을 과장하지 않아요.',
    speech: '쓰임을 알고 고르면 충분해요라고 말해요.',
    want: '재료를 쌓아 두기보다 성질을 이해하는 이웃과 거래하고 싶어요.',
    facts: {
      'sage.use': '맨드레이크는 씨앗의 생명력, 요정 가루는 작은 우연과 관련된다.',
      'sage.exchange': '세이지는 이웃이 서로 씨앗을 나누는 교환회를 연다.',
      'sage.chance': '작은 행운도 원하는 씨앗이나 결과를 보장하지는 않는다.',
    }, story: [
      ResidentStoryBeat(id: 'sage.intro', title: '희귀함보다 쓰임',
        request: '맨드레이크는 잠든 씨앗에 어울려요. 지금 살 필요는 없어요. 로빈의 씨앗 이야기를 들어 보세요.',
        success: '쓰임을 알게 되면 필요한 만큼 고르면 충분해요.',
        revealedFactIds: ['sage.use'], introducedResidentIds: ['robin']),
      ResidentStoryBeat(id: 'sage.luck', title: '표본을 알아보는 눈', potionId: 'luck',
        request: '씨앗 교환회에서 놓쳤던 표본을 알아볼 작은 행운을 부탁해요. 정답을 가져오는 약은 바라지 않아요.',
        success: '원하던 씨앗은 아니었지만 로빈에게 맞는 표본을 발견했어요.',
        revealedFactIds: ['sage.exchange', 'sage.chance']),
      ResidentStoryBeat(id: 'sage.exchange', title: '서로 다른 좋은 씨앗',
        request: '로빈에게 표본을 건네고 키우는 법을 배웠어요. 뜻밖의 교환도 괜찮더군요.',
        success: '씨앗 교환회에서 다른 이웃의 쓰임을 들었어요.',
        introducedResidentIds: ['robin']),
      ResidentStoryBeat(id: 'sage.ending', title: '이야기가 돌아오는 거래',
        request: '이 재료가 어디에 쓰였는지 듣는 게 제일 좋은 거래예요. 조합에도 새 쓰임을 알려 둘게요.',
        success: '세이지는 희귀 재료와 함께 그 쓰임의 이야기도 나누고 있어요.'),
    ]),
  ResidentDefinition(id: 'luna', name: '루나', occupation: '수선사',
    entryCondition: 'guildCompleted',
    personality: '물건을 먼저 살피고 고칠 수 있는 부분부터 찾아요.',
    speech: '이 솔기를 보면요 하고 구체적으로 설명해요.',
    want: '이웃이 낡은 물건을 버리지 않고 다시 쓰도록 돕고 싶어요.',
    facts: {
      'luna.resin': '은나무 수지는 종이와 천에 유연한 막을 만든다.',
      'luna.warmth': '물을 막는 막과 온기를 남기는 약은 하는 일이 다르다.',
      'luna.sign': '수지는 빛나는 재료를 표지판에 붙잡아 줄 수 있다.',
    }, story: [
      ResidentStoryBeat(id: 'luna.raincoat', title: '솔기는 멀쩡한 망토', potionId: 'raincoat',
        request: '이 솔기를 보면 멀쩡하죠? 그런데 비가 스며들어요. 천에 얇은 방수막을 만드는 약이 필요해요.',
        success: '망토를 다시 쓸 수 있게 됐어요. 은나무 수지의 막이 유연하게 붙었네요.',
        revealedFactIds: ['luna.resin']),
      ResidentStoryBeat(id: 'luna.cover', title: '반죽상자의 덮개',
        request: '미나의 덮개도 손봤어요. 온기는 물약이, 찢어진 솔기는 제가 맡으면 되겠네요.',
        success: '약과 수선이 각자의 일을 해 주니 덮개가 다시 제자리를 찾았어요.',
        revealedFactIds: ['luna.warmth'], introducedResidentIds: ['mina']),
      ResidentStoryBeat(id: 'luna.sign', title: '빛을 붙잡는 막',
        request: '엘리 표지판에는 수지로 빛나는 재료를 붙여 보면 어떨까요? 빛의 성질은 연구실에서 살펴보세요.',
        success: '표지판의 빛이 쉽게 떨어지지 않도록 바탕을 손봤어요.',
        revealedFactIds: ['luna.sign'], introducedResidentIds: ['ellie']),
      ResidentStoryBeat(id: 'luna.ending', title: '다시 함께할 물건',
        request: '새것이 된 건 아니에요. 다시 함께할 수 있게 됐죠. 준의 봉투도 한번 살펴볼래요.',
        success: '루나는 이웃의 물건에 다음 이야기가 이어질 자리를 마련해요.',
        introducedResidentIds: ['jun']),
    ]),
  ResidentDefinition(id: 'doran', name: '도란', occupation: '수문지기',
    entryCondition: 'sightFeedback',
    personality: '서두르지 않고 어제와 오늘의 작은 차이를 기억해요.',
    speech: '어제와 소리가 달라요 하며 천천히 설명해요.',
    want: '문제가 커지기 전에 원인을 찾아 이웃에게 설명하고 싶어요.',
    facts: {
      'doran.cold': '도란은 아침의 찬 수문 손잡이에 천을 감아 쓴다.',
      'doran.sound': '수문 철컥 소리 뒤에 작은 떨림이 하나 더 들린다.',
      'doran.repair': '물약은 점검을 돕고, 부품 수리는 도란이 직접 한다.',
    }, story: [
      ResidentStoryBeat(id: 'doran.warmth', title: '찬 아침 손잡이', potionId: 'warmth',
        request: '수문 손잡이가 차서 천을 감았어요. 이 천에 오래가는 온기를 조금 남기고 싶어요.',
        success: '천이 은근히 따뜻해요. 미나도 이 약을 다른 일에 쓴다니 신기하네요.',
        revealedFactIds: ['doran.cold'], introducedResidentIds: ['mina']),
      ResidentStoryBeat(id: 'doran.echo', title: '철컥 뒤의 작은 떨림', potionId: 'echo',
        request: '어제와 소리가 달라요. 작은 기계 진동을 구별할 맑은 메아리 물약을 부탁해요.',
        success: '소리 나는 곳을 찾았어요. 이제 부품은 제가 고칠게요.',
        revealedFactIds: ['doran.sound']),
      ResidentStoryBeat(id: 'doran.repair', title: '내 손으로 하는 정비',
        request: '부품을 갈고 직접 점검했어요. 물약 덕분에 어디를 살필지 알 수 있었죠.',
        success: '오늘은 물소리만 들려요. 엘리에게도 점검서를 전했어요.',
        revealedFactIds: ['doran.repair'], introducedResidentIds: ['ellie']),
      ResidentStoryBeat(id: 'doran.ending', title: '물소리만 들리는 길',
        request: '수문 옆 길을 이웃과 걸어 보려 해요. 앞으로도 제가 직접 살펴볼게요.',
        success: '도란은 조용한 변화에 귀를 기울이며 수문과 길을 돌봐요.'),
    ]),
  ResidentDefinition(id: 'nari', name: '나리', occupation: '도서관 사서',
    entryCondition: 'junFeedbackOrGuild',
    personality: '조용하지만 중요한 뜻은 분명하게 전해요.',
    speech: '여기는 빈칸으로 남겨도 괜찮아요라고 말해요.',
    want: '조용함과 사람의 목소리가 함께 있는 도서관을 만들고 싶어요.',
    facts: {
      'nari.noise': '나리는 사람 목소리 대신 서가의 덜컥거림을 줄이고 싶다.',
      'nari.reading': '나리는 작은 목소리로도 맨 뒤까지 낭독을 전하고 싶다.',
      'nari.scent': '책모임에는 향에 민감한 이웃도 와서 향 없이 준비해도 좋다.',
    }, story: [
      ResidentStoryBeat(id: 'nari.hush', title: '말소리를 남기는 고요', potionId: 'hush',
        request: '문이 닫힐 때 책받침이 달각거려요. 사람 말을 지우지 않고 이 잔향만 줄이고 싶어요.',
        success: '덜컥 소리가 잦아들었어요. 사람들의 작은 대화는 그대로 들리고요.',
        revealedFactIds: ['nari.noise']),
      ResidentStoryBeat(id: 'nari.voice', title: '맨 뒤까지 닿는 이야기', potionId: 'clearvoice',
        request: '작은 목소리로도 맨 뒤까지 이야기를 전하고 싶어요. 부드럽게 울리는 목소리 약이 있을까요?',
        success: '맨 뒤 이웃도 마지막 문장을 들었대요. 크게 소리치지 않아도 됐어요.',
        revealedFactIds: ['nari.reading']),
      ResidentStoryBeat(id: 'nari.invitation', title: '향이 없어도 좋은 초대', potionId: 'calm_scent',
        optional: true, alternativeText: '향 없이 책모임을 준비해요',
        request: '준은 초대장을, 미나는 간식을 챙겨 준대요. 향에 민감한 이웃도 오니 향 없이 준비해도 좋아요.',
        success: '모두 편한 자리를 골랐어요. 향이 있고 없고보다 함께 듣는 시간이 좋았어요.',
        revealedFactIds: ['nari.scent'], introducedResidentIds: ['jun', 'mina']),
      ResidentStoryBeat(id: 'nari.ending', title: '듣기만 해도 이웃',
        request: '오늘 빈 의자가 하나도 없었어요. 말하지 않고 듣기만 한 이웃도요. 다음에도 함께 읽고 싶어요.',
        success: '나리의 책모임에는 조용히 들어도 괜찮은 자리가 있어요.'),
    ]),
];

ResidentDefinition residentById(String id) => residents.firstWhere((r) => r.id == id);
